### ISSUE TITLE
Headers name is send lower case

### ISSUE THREAD

**Issue by MaximeWeyl** [frigus02/RESTer#72]
Hello,
When I try to use this header name "X-Gitlab-Token", rester make the request using "x-gitlab-token" (lower case). 
When Gitlab does his request, it is not in lower case, so I'm not able to mimic gitlab's behaviour using RESTer (without using workarounds in my code).

**Comment by frigus02** [comment]
Sorry for the late response. This sounds similar to #47 and was fixed in RESTer 3.4.0. Which version of RESTer were you using when you had this problem?

**Comment by MaximeWeyl** [comment]
I am on the latest (3.9.0) version and I still reproduce the bug. 
I use this webapp to test it : https://webhook.site/
(previously I was on my own app).

Any uppercase character in the header's key seems to be sent in lowercase.

**Comment by frigus02** [comment]
Hm, this is really weird. In my tests with a custom echo server ([tools/dev-utils/server.js](https://github.com/frigus02/RESTer/blob/master/tools/dev-utils/server.js), [tools/lib/server.js](https://github.com/frigus02/RESTer/blob/master/tools/lib/server.js)) I can see headers from RESTer, Firefox, Chrome and PowerShell curl coming in as I type them with the correct upper and lowercase characters.

For me https://webhook.site shows all headers in lowercase, no matter how I call it. Not sure if that's a problem on my side.

Another question, since I'm testing on Windows currently: what operating system are you running?

**Comment by frigus02** [comment]
I fixed another issue with headers  in #75, which may also fix your. I'm going to close this now. But feel free to reopen it, if your issue still persists.
